name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - shell: bash
        env:
          EMPORIO_SECRET: ${{ secrets.emporio }}
        run: |
          echo $EMPORIO_SECRET
          sed -i "s/{{secrets.emporio}}/$EMPORIO_SECRET/" nuget.config
          cat nuget.config
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
